### ISSUE TITLE
Script to register tentacles 

### ISSUE THREAD

**Issue by Dalmirog** [Dalmirog/OctopusDeploy-Powershell-module#20]

**Comment by Dalmirog** [comment]
Tentacle.exe already does this

**Comment by ThaddParker** [comment]
could there be a script snippet that could call the tentacle exe remotely given a environment id or group of environment ids?

**Comment by Dalmirog** [comment]
Hi Thadd,

On **0.2.0** I'll add 2 cmdlets called **Get-OctopusEnvironment** and **Get-OctopusMachine** that'll let you filter by EnvironmentID/s. These cmdlets will help you get the tentacle's URL among other stuff (thumbprints, communicationstyle). With that URL you can easily create a loop to remote into each tentacle and run *tentacle.exe*. 

I can even help you building that script once **0.2.0** is out.

**Comment by ThaddParker** [comment]
I already have the c# version that I am translating to PS.  I also forked
the dev branch to add a Get-OctopusStatisticsReport (translated from c#).
I will talk to you about all of that later. cheers.
